version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eroom-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/eroom
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: mariadb:10.9
    container_name: eroom-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eroom
    volumes:
      - db-data:/var/lib/mysql

  ngrok-app:
    image: ngrok/ngrok:latest
    container_name: ngrok-app
    restart: unless-stopped
    ports:
      - "4040:4040"  # ngrok 대시보드용 포트
    environment:
      NGROK_AUTHTOKEN: "2tVen5h9eLjIaUey5wvrK0PuBb7_4shk9dp3f9ibktsgj2Wa6"
    command:
      - http
      - --log=stdout
      - eroom-app:8080 # 기존의 host.docker.internal:8080를 Docker 네트워크 안의 eroom-app을 바라보도록 수정 (Docker 네트워크 내 eroom-app 컨테이너로 직접 연결)

  ngrok-jenkins:
    image: ngrok/ngrok:latest
    container_name: ngrok-jenkins
    restart: unless-stopped
    ports:
      - "4041:4040"  # 두 번째 ngrok 대시보드
    environment:
      NGROK_AUTHTOKEN: "2tVen5h9eLjIaUey5wvrK0PuBb7_4shk9dp3f9ibktsgj2Wa6"
    command:
      - http
      - --log=stdout
      - host.docker.internal:8090

volumes:
  db-data:
